General:
  WindowWidth: 750
  WindowHeight: 700
  WindowOffset: 50

Path:
  BackgroundMusic: ../asset/sounds/golden_wind.mp3
  BossMusic: ../asset/sounds/golden_wind_boss.mp3
  ExplosionSound: ../asset/sounds/explosion.ogg
  BossWarningSound: ../asset/sounds/warning.mp3
  LaserSound: ../asset/sounds/laser.ogg
  Alien_1_Img: ../asset/graphics/alien_1.png
  Alien_2_Img: ../asset/graphics/alien_2.png
  Alien_3_Img: ../asset/graphics/alien_3.png
  Alien_4_Img: ../asset/graphics/alien_4.png
  MysteryShipImg: ../asset/graphics/mystery.png
  SpaceShipImg: ../asset/graphics/spaceship.png
  Font: ../asset/font/monogram.ttf
  HighScore: ./highscore.txt

Menu:
  MainMenu:
    ButtonXMargin: 400
    ButtonYMargin: 300
    ButtonWidth: 400
    ButtonHeight: 100
    ButtonYGap: 50
    ButtonTexts: ["Start", "Level ", "Exit", "+", "-"]
    ButtonOnColor: ["Blue", "Blue", "Blue", "Green", "Red"]
    ButtonOffColor: ["Orange", "Orange", "Orange", "Orange", "Orange"]
  OptionList:
    ButtonXMargin: 300
    ButtonYMargin: 400
    ButtonWidth: 300
    ButtonHeight: 70
    ButtonYGap: 30
    ButtonTexts: ["ReStart", "Next", "Menu", "Exit"]
    ButtonOnColor: ["Blue", "Blue", "Blue", "Blue"]
    ButtonOffColor: ["Orange", "Orange", "Orange", "Orange"]
  BossMenu:
    ButtonXMargin: 100
    ButtonYMargin: 300
    ButtonWidth: 600
    ButtonHeight: 150
    ButtonTexts: ["Warning"]
    ButtonOnColor: ["Red"]

Game:
  General:
    Lives: 3
    RewardDisplayInterval: 2
    BossMenuDisplayInterval: 5
    MusicVolume: 0.25
  SpaceShip:
    Speed: 6
    FireInterval: 0.5
    LaserSpeed: -6
  MysteryShip:
    Speed: 3
  Reward:
    Alien: [100, 200, 300]
    MysteryShip:
      AddScore: 500
      AddMove: 2
      AddLive: 1
      ReduceFireIntervalFactor: 1.5
      AddLaserSpeed: 2
  
  LEVEL1:
    Obstacle:
      NumObstacles: 5
    Alien:
      Rows: 1
      Cols: 1
      Speed: 1
      DropDistance: 6
      FireInterval: 0.5
      LaserSpeed: 6
    MysteryShip:
      SpawnIntervalLowerBound: 5
      SpawnIntervalUpperBound: 10
    Boss:
      Live: 5
      Speed: 3
      Scale: 3
      FireInterval: 0.4
      LaserSpeed: 6
  
  LEVEL2:
    Obstacle:
      NumObstacles: 4
    Alien:
      Rows: 2
      Cols: 2
      Speed: 2
      DropDistance: 6
      FireInterval: 0.4
      LaserSpeed: 6
    MysteryShip:
      SpawnIntervalLowerBound: 5
      SpawnIntervalUpperBound: 10
    Boss:
      Live: 10
      Speed: 3
      Scale: 4
      FireInterval: 0.3
      LaserSpeed: 6
  
  LEVEL3:
    Obstacle:
      NumObstacles: 3
    Alien:
      Rows: 6
      Cols: 10
      Speed: 2
      DropDistance: 8
      FireInterval: 0.4
      LaserSpeed: 7
    MysteryShip:
      SpawnIntervalLowerBound: 5
      SpawnIntervalUpperBound: 10
    Boss:
      Live: 15
      Speed: 3
      Scale: 5
      FireInterval: 0.3
      LaserSpeed: 7

      
