General:
  WindowWidth: 750
  WindowHeight: 700
  WindowOffset: 50

Path:
  BackgroundMusic: ../asset/sounds/golden_wind.mp3
  ExplosionSound: ../asset/sounds/explosion.ogg
  LaserSound: ../asset/sounds/laser.ogg
  Alien_1_Img: ../asset/graphics/alien_1.png
  Alien_2_Img: ../asset/graphics/alien_2.png
  Alien_3_Img: ../asset/graphics/alien_3.png
  MysteryShipImg: ../asset/graphics/mystery.png
  SpaceShipImg: ../asset/graphics/spaceship.png
  Font: ../asset/font/monogram.ttf
  HighScore: ./highscore.txt

Menu:
  MainMenu:
    ButtonXMargin: 400
    ButtonYMargin: 300
    ButtonWidth: 400
    ButtonHeight: 100
    ButtonYGap: 50
    ButtonTexts: ["Start", "Level ", "Exit", "+", "-"]
    ButtonOnColor: ["Blue", "Blue", "Blue", "Green", "Red"]
    ButtonOffColor: ["Orange", "Orange", "Orange", "Orange", "Orange"]
  OptionList:
    ButtonXMargin: 300
    ButtonYMargin: 400
    ButtonWidth: 300
    ButtonHeight: 70
    ButtonYGap: 30
    ButtonTexts: ["ReStart", "Next", "Menu", "Exit"]
    ButtonOnColor: ["Blue", "Blue", "Blue", "Blue"]
    ButtonOffColor: ["Orange", "Orange", "Orange", "Orange"]

Game:
  General:
    Lives: 3
    RewardDisplayInterval: 2
    MusicVolume: 0.25
  SpaceShip:
    Speed: 6
    FireInterval: 0.5
  MysteryShip:
    Speed: 3
  Laser:
      SpaceshipLaserSpeed: -6
  Reward:
    Alien: [100, 200, 300]
    MysteryShip:
      AddScore: 500
      AddMove: 2
      AddLive: 1
      ReduceFireIntervalFactor: 1.5
      AddLaserSpeed: 2
  
  LEVEL1:
    Obstacle:
      NumObstacles: 5
    Alien:
      AlienRows: 3
      AlienCols: 5
      AlienSpeed: 1
      AlienDropDistance: 6
      FireInterval: 0.5
    MysteryShip:
      MysteryshipSpawnIntervalLowerBound: 5
      MysteryshipSpawnIntervalUpperBound: 10
      Speed: 3
    Laser:
      AlienLaserSpeed: 6
  
  LEVEL2:
    Obstacle:
      NumObstacles: 4
    Alien:
      AlienRows: 4
      AlienCols: 10
      AlienSpeed: 2
      AlienDropDistance: 6
      FireInterval: 0.4
    MysteryShip:
      MysteryshipSpawnIntervalLowerBound: 5
      MysteryshipSpawnIntervalUpperBound: 10
      Speed: 3
    Laser:
      AlienLaserSpeed: 6
  
  LEVEL3:
    Obstacle:
      NumObstacles: 3
    Alien:
      AlienRows: 6
      AlienCols: 10
      AlienSpeed: 2
      AlienDropDistance: 8
      FireInterval: 0.4
    MysteryShip:
      MysteryshipSpawnIntervalLowerBound: 5
      MysteryshipSpawnIntervalUpperBound: 10
      Speed: 3
    Laser:
      AlienLaserSpeed: 7
      
